### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by Naami786** [VBA-tools/VBA-UTC#10]
The snippet code is not generating the snipes, needs to be updated.

**Comment by Nick-vanGemeren** [comment]
This software is not involved in the making of pyjamas or other softwear.  Please explain your issue.
If you have posted to the wrong place, please close this issue.

**Comment by Naami786** [comment]
The snipes are needed to be generated in order to make sure the indefinite changes in the #6 and #7 library so its better to go with generator tubuntu.io
