### ISSUE TITLE
Add: Issue parsing ISO date strings with offsets

### ISSUE THREAD

**Issue by chackl1990** [VBA-tools/VBA-UTC#4]
Problem still seems not solved.
I corrected it by using:
`ParseIso = ParseIso - utc_Offset`
instead of
`ParseIso = ParseIso + utc_Offset`

2017-12-29T23:12:48.813+01:00 should be 2017-12-29 23:12:48 in my timezone +01:00 Vienna.
The Offset is not added - it must be inverted (as i saw on wiki).

**Comment by timhall** [comment]
Thanks for raising this issue. Looking at the tests, it does seem to be going negative twice (`-240` initially and then `TZOffsetHours = Int(-OffSetMinutes / 60)`). This does seem like a mistake and could be why your issue wasn't caught (and why it's backwards). I'll take a look at it.
